# Generated by Django 3.1.7 on 2021-04-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
                ('picture', models.CharField(max_length=200, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('fuel_usage', models.FloatField(default=0)),
                ('deposit', models.IntegerField(default=500)),
                ('additional_info', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserv', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_return', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.moto')),
            ],
        ),
        migrations.CreateModel(
            name='PriceIncrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent1_3', models.FloatField(default=20)),
                ('percent4_6', models.FloatField(default=15)),
                ('percent7_13', models.FloatField(default=10)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.moto')),
            ],
        ),
    ]
