# Generated by Django 3.1.7 on 2021-04-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210419_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='quantity',
        ),
        migrations.AddField(
            model_name='moto',
            name='license',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('A1', 'A1'), ('A2', 'A2'), ('A', 'A')], default='A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='additional_info',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
